package Bank.Operations

enum OperationType {
    WITHDRAWAL, PAYMENT, CREATE_ACCOUNT, CALCULATE_INTEREST, CHANGE_INTEREST_RATE, CREATE_DEPOSIT, CLOSE_DEPOSIT,
    CREATE_LOAN, REPAY_LOAN, CREATE_REPORT
}
